### ISSUE TITLE
User Model

### ISSUE THREAD

**Issue by echjordan** [echjordan/dunder_mifflin#10]
add Cart ARRAY OF Product Id's
Email STRING validation for unique email (taken care of by is email?)
Password (somehow encrypted, we don't want to store this) STRING
Auth things --> (salt and/or googleId?)

Name STRING
Admin BOOLEAN

**ADMIN FEATURE
trigger password reset for a user on next log in

**Comment by aprilrueb** [comment]
Not adding "add Cart ARRAY OF Product Id's"
