### ISSUE TITLE
Order Model

### ISSUE THREAD

**Issue by echjordan** [echjordan/dunder_mifflin#11]
Order Status (Create, Processing, Cancelled, Completed) STRING
Subtotal DECIMAL(10,2)
Date/Time created DATE
Items ARRAY of OBJECTS containing Product Id and Quantity
Shipping Address STRING
Email STRING, with EMAIL VALIDATION

Instance Methods
//ADMIN FEATURES
Update status of an order, dispatch email to update status

**Comment by EHenry92** [comment]
--Admin feature dispatch email may be something we have to implement in the javaScript portion of the admin
