### ISSUE TITLE
Mon Bug Fixes

### ISSUE THREAD

**Issue by echjordan** [echjordan/dunder_mifflin#41]
admins can edit products (name, quantity, price, description)

redirect based on history after logging in to single product -- can use redirect param in URL
integrate with stripe
_add name field to sign up form, title for sign up_

**Comment by echjordan** [comment]
reopen

**Comment by aprilrueb** [comment]
Should not be able to add products to cart that aren't available

**Comment by echjordan** [comment]
close

**Comment by echjordan** [comment]
closes #61
